import type { Metadata } from 'next';
import { Inter, Rubik } from 'next/font/google';
import './globals.css';
import Main from '@/components/Main';
import Header from '@/components/Header';

const inter = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Pokedex',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				<Main>{children}</Main>
			</body>
		</html>
	);
}
